# Copyright 2023 The Sky Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The main class for defining and running an app."""

import asyncio
import dataclasses
import functools
import logging
import os
import time
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, Union

from sky import global_user_state
from sky import skypilot_config
from sky.skylet import constants
from sky.skylet import resources
from sky.skylet import task
from sky.skylet import utils
from sky.skylet.providers.aws import aws_utils
from sky.skylet.providers.aws import aws_utils_async
from sky.skylet.providers.aws import aws_utils_sync
from sky.skylet.providers.aws import aws_utils_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_async
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync
from sky.skylet.providers.aws import aws_utils_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async_lock_sync_async